name: PlayerCustomDisplay
version: '1.0'
main: com.example.pcd.main
api-version: '1.21'
authors: [ Mike4947 ]
description: Customizes the server list display and tab list.

commands:
  pcd:
    description: Main command for PlayerCustomDisplay.
    usage: /pcd <set | setmax | hover | stat | reload>
    permission: playercustomdisplay.admin

permissions:
  playercustomdisplay.admin:
    description: Allows using all PlayerCustomDisplay commands.
    default: op