name: PlayerCustomDisplay
version: '1.0'
main: com.example.pcd.main
api-version: '1.21'
authors: [ Mike4947 ]
description: Sets a custom player count in the server list.

commands:
  pcd:
    description: Main command for PlayerCustomDisplay.
    usage: /pcd set <number>
    permission: playercustomdisplay.admin

permissions:
  playercustomdisplay.admin:
    description: Allows setting the custom player count.
    default: op